import type { PartnerConfig } from "./types";

export const defaultPartner: PartnerConfig = {
  id: "default",
  brand: {
    name: "Agent Swap",
    iconSrc: "/favicon.ico",
    appleIconSrc: "/icon.png",
    logoAlt: "Agent Swap",
    externalUrl: "https://www.orbs.com/",
    metadata: {
      title: "Agent Swap",
      description: "A white-label intent-powered swap and advanced order app.",
      url: "https://www.orbs.com/",
    },
  },
  styles: {
    radius: "0.625rem",
    fontFamily:
      'Roboto, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    colors: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#171717",
      cardForeground: "#fafafa",
      popover: "#171717",
      popoverForeground: "#fafafa",
      primary: "#ff37c7",
      primaryForeground: "#ffffff",
      secondary: "#262626",
      secondaryForeground: "#fafafa",
      muted: "#262626",
      mutedForeground: "#a1a1a1",
      accent: "#212121",
      accentForeground: "#fafafa",
      destructive: "#ff6568",
      border: "rgba(255, 255, 255, 0.1)",
      input: "rgba(255, 255, 255, 0.15)",
      ring: "#737373",
      chart1: "#1447e6",
      chart2: "#00bb7f",
      chart3: "#f99c00",
      chart4: "#ac4bff",
      chart5: "#ff2357",
      sidebar: "#171717",
      sidebarForeground: "#fafafa",
      sidebarPrimary: "#1447e6",
      sidebarPrimaryForeground: "#fafafa",
      sidebarAccent: "#262626",
      sidebarAccentForeground: "#fafafa",
      sidebarBorder: "rgba(255, 255, 255, 0.1)",
      sidebarRing: "#737373",
    },
  },
};
