import type { PartnerConfig } from "./types";

export const gincoPartner: PartnerConfig = {
  id: "ginco",
  brand: {
    name: "Ginco Enterprise Wallet",
    logoSrc: "/ginco-logo.svg",
    navLogoClassName: "h-5 max-w-[138px] sm:h-6 sm:max-w-[178px]",
    iconSrc: "/ginco-icon.svg",
    appleIconSrc: "/ginco-icon.svg",
    logoAlt: "Ginco Enterprise Wallet",
    metadata: {
      title: "Ginco Enterprise Wallet",
      description:
        "A wallet screen for managing digital asset wallets by creation status and currency.",
    },
  },
  styles: {
    radius: "0.25rem",
    fontFamily:
      'Inter, "Noto Sans JP", "Hiragino Sans", "Yu Gothic", Meiryo, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    selectedTabBackground: "#ffffff",
    selectedTabForeground: "#161b2f",
    selectedTabRadius: "2px",
    selectedTabShadow: "0 1px 2px rgba(22, 27, 47, 0.06)",
    navBackground: "#ffffff",
    controlRadius: "2px",
    formContainerBackground: "#ffffff",
    formContainerBorder: "rgba(22, 27, 47, 0.08)",
    formContainerRadius: "21px",
    formPanelBackground: "#fafafa",
    formPanelBorder: "rgba(22, 27, 47, 0.1)",
    formPanelRadius: "18px",
    submitButtonRadius: "2px",
    tabListBackground: "#eeeeef",
    tabListBorder: "rgba(22, 27, 47, 0.08)",
    tabListRadius: "2px",
    settingsTriggerBackground: "#ffffff",
    settingsTriggerHoverBackground: "#f2f3f5",
    settingsTriggerForeground: "#2878e3",
    colors: {
      background: "#f4f4f4",
      foreground: "#05043a",
      card: "#ffffff",
      cardForeground: "#161b2f",
      popover: "#ffffff",
      popoverForeground: "#161b2f",
      primary: "#2878e3",
      primaryForeground: "#ffffff",
      secondary: "#f1f2f4",
      secondaryForeground: "#161b2f",
      muted: "#f6f7f8",
      mutedForeground: "#767d8a",
      accent: "#edf0f3",
      accentForeground: "#05043a",
      destructive: "#d64545",
      border: "rgba(22, 27, 47, 0.12)",
      input: "rgba(22, 27, 47, 0.18)",
      ring: "#2878e3",
      chart1: "#2878e3",
      chart2: "#102338",
      chart3: "#34a878",
      chart4: "#8b5cf6",
      chart5: "#f59e0b",
      sidebar: "#102338",
      sidebarForeground: "#ffffff",
      sidebarPrimary: "#2878e3",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#0b1828",
      sidebarAccentForeground: "#ffffff",
      sidebarBorder: "rgba(255, 255, 255, 0.14)",
      sidebarRing: "#2878e3",
    },
  },
};
