import type { PartnerConfig } from "./types";

// Palette, Montserrat typography and square controls from orbs-website-v2.vercel.app.
// Surface roles follow the site's surface/card-fill tokens; secondary stays neutral
// here because the trading UI uses it for inset panels, rather than accent buttons.
export const orbsPartner: PartnerConfig = {
  id: "orbs",
  features: { customConnectModal: false },
  brand: {
    name: "Orbs",
    navWordmark: "Orbs",
    logoSrc: "/orbs-logo.svg",
    navLogoClassName: "!size-7",
    iconSrc: "/orbs-logo.svg",
    appleIconSrc: "/icon.png",
    logoAlt: "Orbs",
    externalUrl: "https://www.orbs.com/",
    metadata: {
      title: "Orbs | Swap & Advanced Orders",
      description: "Swap tokens and trade with advanced orders, powered by Orbs.",
      url: "https://www.orbs.com/",
    },
  },
  styles: {
    radius: "0rem",
    fontFamily: '"Orbs Montserrat", Montserrat, ui-sans-serif, system-ui, sans-serif',
    controlRadius: "0px",
    formContainerRadius: "0px",
    formPanelRadius: "0px",
    submitButtonRadius: "0px",
    tabListRadius: "0px",
    selectedTabRadius: "0px",
    selectedTabBackground: "#121214",
    selectedTabForeground: "#f6f6f6",
    navBackground: "#f6f6f6",
    formContainerBackground: "#ffffff",
    formPanelBackground: "#f6f6f6",
    tabListBackground: "#f6f6f6",
    settingsTriggerBackground: "transparent",
    settingsTriggerHoverBackground: "#e2e2e2",
    settingsTriggerForeground: "#121214",
    colors: {
      background: "#f6f6f6",
      foreground: "#121214",
      card: "#ffffff",
      cardForeground: "#121214",
      popover: "#ffffff",
      popoverForeground: "#121214",
      primary: "#3346f2",
      primaryForeground: "#ffffff",
      secondary: "#f6f6f6",
      secondaryForeground: "#121214",
      muted: "#e2e2e2",
      mutedForeground: "#59595a",
      accent: "#e2e2e2",
      accentForeground: "#121214",
      destructive: "#664344",
      border: "#e2e2e2",
      input: "#e2e2e2",
      ring: "#3346f2",
      chart1: "#3346f2",
      chart2: "#125f65",
      chart3: "#58375a",
      chart4: "#8165c7",
      chart5: "#cc8788",
      sidebar: "#ffffff",
      sidebarForeground: "#121214",
      sidebarPrimary: "#3346f2",
      sidebarPrimaryForeground: "#ffffff",
      sidebarAccent: "#e2e2e2",
      sidebarAccentForeground: "#121214",
      sidebarBorder: "#e2e2e2",
      sidebarRing: "#3346f2",
    },
    themeOverrides: {
      dark: {
        selectedTabBackground: "#f6f6f6",
        selectedTabForeground: "#121214",
        navBackground: "#121214",
        formContainerBackground: "#1e1e20",
        formPanelBackground: "#29292b",
        tabListBackground: "#29292b",
        settingsTriggerHoverBackground: "#414142",
        settingsTriggerForeground: "#f6f6f6",
        colors: {
          background: "#121214",
          foreground: "#f6f6f6",
          card: "#29292b",
          cardForeground: "#f6f6f6",
          popover: "#29292b",
          popoverForeground: "#f6f6f6",
          primary: "#7a89e9",
          primaryForeground: "#121214",
          secondary: "#29292b",
          secondaryForeground: "#f6f6f6",
          muted: "#414142",
          mutedForeground: "#c5c5c5",
          accent: "#414142",
          accentForeground: "#f6f6f6",
          destructive: "#cc8788",
          border: "#414142",
          input: "#414142",
          ring: "#7a89e9",
          chart1: "#7a89e9",
          chart2: "#2cedfc",
          chart3: "#dc8ae0",
          chart4: "#a17ae9",
          chart5: "#ffadae",
          sidebar: "#29292b",
          sidebarForeground: "#f6f6f6",
          sidebarPrimary: "#7a89e9",
          sidebarPrimaryForeground: "#121214",
          sidebarAccent: "#414142",
          sidebarAccentForeground: "#f6f6f6",
          sidebarBorder: "#414142",
          sidebarRing: "#7a89e9",
        },
      },
    },
  },
};
